name: Build and Test Docker Image

on:
  push:
    branches:
      - main

jobs:
  test-cron-container:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository name
        run: |
          echo "REPOSITORY_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t cron-container .

      - name: Test Docker image
        run: |
          echo $REPOSITORY_NAME
          docker run --rm \
            -e PAT_TOKEN=${{ secrets.PAT_TOKEN }} \
            -e USER_NAME=${{ github.actor }} \
            -e REPOSITORY_NAME=env.REPOSITORY_NAME \
            env.REPOSITORY_NAME
